import test.entityTest.BubbleSortEntity_Test
import test.entityTest.BubbleSortEntity_Test.sortAscendingWithIntermediateResults_should_return
import test.entityTest.BubbleSortEntity_Test.sortDescendingWithIntermediateResults_should_return
import test.entityTest.BubbleSortEntity_Test.sortOnceWithIntermediateResults_should_return

class Entity_TestImpl extends TestUtil:

	implementTest(BubbleSortEntity_Test, sortAscendingWithIntermediateResults_should_return)
	implementTest(BubbleSortEntity_Test, sortDescendingWithIntermediateResults_should_return)
	implementTest(BubbleSortEntity_Test, sortOnceWithIntermediateResults_should_return)